# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: vendor/
      linters: ["*"]
